packages:
  - client/core
  - client/react
  - client/angular
  - client/angular/projects/traceviz-angular
  - logviz/client

onlyBuiltDependencies:
  - '@parcel/watcher@2.5.4'
  - esbuild@0.20.1
  - esbuild@0.20.2
  - esbuild@0.21.5
  - less@4.5.1
  - nice-napi@1.0.2
