packages:
  - client/core
  - client/react
  - client/angular
  - client/angular/projects/traceviz-angular
  - causal_tracing/react-client
  - logviz/angular-client
  - logviz/react-client

nodeLinker: hoisted
minimumReleaseAge: 10080

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  nice-napi: true
